"""add_password_reset_fields

Revision ID: 1dbfb3c7cf34
Revises: 004_migrate_to_paystack
Create Date: 2026-01-05 19:15:57.299145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dbfb3c7cf34'
down_revision: Union[str, None] = '004_migrate_to_paystack'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assessment_purchases_evaluation_id_key', 'assessment_purchases', type_='unique')
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_users_paystack_customer_code', table_name='users')
    op.create_index(op.f('ix_users_password_reset_token'), 'users', ['password_reset_token'], unique=False)
    op.create_unique_constraint(None, 'users', ['paystack_customer_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_password_reset_token'), table_name='users')
    op.create_index('ix_users_paystack_customer_code', 'users', ['paystack_customer_code'], unique=True)
    op.drop_column('users', 'password_reset_expires')
    op.drop_column('users', 'password_reset_token')
    op.create_unique_constraint('assessment_purchases_evaluation_id_key', 'assessment_purchases', ['evaluation_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###

